# Generated by Django 3.2.9 on 2022-04-26 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220426_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='arrival',
        ),
        migrations.RemoveField(
            model_name='boat',
            name='departure',
        ),
    ]
