# Generated by Django 3.2.9 on 2022-05-07 13:51

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220426_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='jetty_pictures',
            name='medium_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, size=[500, 300], upload_to='medium_jetty'),
        ),
        migrations.AddField(
            model_name='jetty_pictures',
            name='small_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, size=[100, 100], upload_to='small_jetty'),
        ),
        migrations.AlterField(
            model_name='jetty_pictures',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, size=[1920, 1080], upload_to='jetty'),
        ),
    ]
