# Generated by Django 3.2.9 on 2022-05-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220507_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Boat_type_or_name', models.TextField(blank=True)),
                ('accident_time', models.DateTimeField(blank=True)),
                ('location', models.CharField(blank=True, max_length=254)),
                ('number_of_casuality', models.IntegerField(blank=True)),
                ('number_of_injuries', models.IntegerField(blank=True)),
                ('number_of_death', models.IntegerField(blank=True)),
                ('number_of_rescues', models.IntegerField(blank=True)),
                ('cause', models.TextField(blank=True)),
            ],
        ),
    ]
