# Generated by Django 3.2.9 on 2022-05-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_accident'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='accident_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='boat_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='accident_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='boat_type',
            field=models.CharField(blank=True, choices=[('Wooden', 'Wooden'), ('Fiber', 'Fiber'), ('Aluminium', 'Aluminiun'), ('Steel', 'Steel'), ('Others', 'Others')], default=None, max_length=254),
        ),
    ]
