# Generated by Django 3.2.9 on 2022-06-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_jetty_pictures_header_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jetty_bathymetry',
            name='bathymetry',
            field=models.FileField(upload_to='bathymetry'),
        ),
    ]
